### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by dulajra** [roryrjb/md5-file#15]
Not working in windows.

But after commenting the first line which is `#!/usr/bin/env node` of the `node_modules\md5-file\index.js` it works fine.

**Comment by LinusU** [comment]
Would you mind testing if #16 fixes this for you?

You can install it by running `npm install roryrjb/md5-file#2e59275`

**Comment by dulajra** [comment]
This is not a problem with 'md5-file' node module itself. I'm using this md5-file within an electron app. Sorry for the inconvenience caused
