### ISSUE TITLE
You can use pipe

### ISSUE THREAD

**Issue by LinusU** [roryrjb/md5-file#2]
You can `.pipe` the `fileStream` directly to the hash instead of using `update`.

```javascript
fileStream.pipe(sum)
```

**Comment by LinusU** [comment]
Hi @roryrjb, I saw that you added me as a collaborator to the project, nice 👍 

I'd be happy to help out as a maintainer, could you also add me on npm? My username is [`linusu`](https://npmjs.org/~linusu) there.

**Comment by roryrjb** [comment]
@LinusU done!

**Comment by LinusU** [comment]
Thanks

**Comment by LinusU** [comment]
Fixed in c9e17944d9ab4fa78fc6162ac669a304b1550f8b, released as 2.0.5
