### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by roryrjb** [roryrjb/md5-file#24]
I don't use this module anymore, and to be honest I don't even use Node.js or GitHub much anymore, and I don't have the time to update it, review issues or pull requests, so I am looking for a new maintainer. I won't just pick anyone, as people are using the module, so I have to ensure it goes into good hands. If no one suitable comes forward (in a reasonable amount of time) I will deprecate the module in npm and archive the repo in GitHub.

**Comment by roryrjb** [comment]
@LinusU obviously you are first choice (although I imagine you are too busy) and it's mainly about it not being under my name, up to you.

Also pinging contributors: @realityking @kodie.

**Comment by bryantbiggs** [comment]
@roryrjb I can help if needed. I can host under my personal (@bryantbiggs) or professional (@clowdhaus - currently most of which is private) - let me know, I'd love to help and keep it going

**Comment by roryrjb** [comment]
Hey @bryantbiggs, many thanks for the offer!

I'm not making any firm decisions just yet but will let you know.
Do you have an npm account as well? As I would also need to add you as a
maintainer there.

-- 
Rory Bradford <rory@dysfunctionalprogramming.com>
7403 D90D D28E C32B 2562 1BA2 23A7 2C05 0145 EFA8

**Comment by bryantbiggs** [comment]
yes - 
personal: https://www.npmjs.com/~bryantbiggs
professional: https://www.npmjs.com/org/clowd.haus

**Comment by andrasbacsai** [comment]
Hi @roryrjb,
We can help you to maintain this in our [organization](https://www.npmjs.com/org/coollabsio), if needed.

Our goal is, inter alia, to maintain open source repositories which have absence of maintainers, but important for the open source community.

So feel free to contact us / me.

**Comment by kodie** [comment]
@roryrjb I'd love to help maintain md5-file!

**Comment by roryrjb** [comment]
@kodie as you are already a contributor you have first refusal imo. I've added you as a maintainer on GitHub and npm. Do you want the repository moved to your user on GitHub?

**Comment by roryrjb** [comment]
I've also removed the deprecation message (_"This module is looking for a new maintainer"_) on npm.

**Comment by kodie** [comment]
@roryrjb Sure we can move it over to mine if you don't plan on being involved anymore. I'm also on NPM with the same username.

**Comment by roryrjb** [comment]
@kodie cool, thanks really appreciate this. I just tried to move it over but it won't let me because you already have your `md5-file` fork, if you delete or rename it I can then move it over.

**Comment by kodie** [comment]
@roryrjb Awesome! I just deleted my fork.

**Comment by roryrjb** [comment]
@kodie ok done. Thanks again.

**Comment by LinusU** [comment]
I would be happy to still help out as well! I believe that I have access to the npm already

**Comment by roryrjb** [comment]
@LinusU thank you. You should still have write access to this repo (even after it's moved over) and npm.
