### ISSUE TITLE
A question about uniqueness

### ISSUE THREAD

**Issue by RezaRahmati** [roryrjb/md5-file#32]
Is it possible that two files that are not same have same hash result?

**Comment by LinusU** [comment]
Technically, that is possible with any hash algorithm in the entire world, as the output hash is a fixed size and there is an infinite number of possible inputs.

That being said, md5 isn't the strongest hash and it's possible to craft collisions, see here for more info: https://en.wikipedia.org/wiki/MD5#Collision_vulnerabilities
