### ISSUE TITLE
Include the path of the file when generating the file's hash to prevent duplicate hashes when files have no content of their own.

### ISSUE THREAD

**Issue by jeffschwartz** [roryrjb/md5-file#33]
I noticed that files with no content of their own all had the same hash. Would it be possible to include the file path when generating their hashes to guarantee that all files, including those with no content, all have unique hashes?

**Comment by LinusU** [comment]
That would make two identical files have different hashes, and would also make us incompatible with other tools like the `md5` cli. It would also make the hash change if you rename the file, which doesn't seem desirable.

What is your use case?

**Comment by jeffschwartz** [comment]
Thank you, @LinusU, for your response. My use case is as follows: My cache busting utility [Buster](https://github.com/4awpawz/buster) uses the md5-file package to fingerprint file names. Users of Buster have noticed that empty files were causing their builds to break. Of course I told them that Buster fingerprints files based on their content but as a web developer myself I know that there are times when a web or browser asset, such as a javascript file, may not contain content due to the state of development that the project is on. The inclusion of file names, perhaps as an additional option, would alleviate this issue.

In all fairness I think I could just swap out the md5-file package with the md5 package as it accepts content rather than file paths.

What do you think, would user's of md5-file benefit from an option like this?

**Comment by LinusU** [comment]
Hmm, in what way does the build break? It seems like the same would happen if two files contains the same text then?

You could use the `md5` package directly, but I would advise you to get to the bottom of what exactly the issue is. If two files have the exact same content, isn't it good that it produces the same hash? Since the content will be the same you only need to download the content once instead of twice 🤔

**Comment by jeffschwartz** [comment]
Yes I totally agree but I was looking to decrease the frequency that I am asked about this 😹. Your point is so well raised that I have decided to make this explicitly clear in Buster's README.md file.

Thank you for taking the time to help me come to a resolution on this. I will close out this issue now.
