### ISSUE TITLE
Change api to have two separate functions

### ISSUE THREAD

**Issue by LinusU** [roryrjb/md5-file#5]
I think it would be nicer if the api looked like this:

```js
// Async
md5File('LICENSE.md', (err, hash) => {})

// Sync
md5File.sync('LICENSE.md')
```

This seems to be where the community landed, and there are a lot of high profile packages (see below) following this style. By following this style, we adhere to the [Principle_of_least_astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

- [rimraf](https://www.npmjs.com/package/rimraf)
- [mkdirp](https://www.npmjs.com/package/mkdirp)
- [glob](https://www.npmjs.com/package/glob)
- [del](https://www.npmjs.com/package/del)

It would also allow us to have more strict arguments validation 🙌

**Comment by roryrjb** [comment]
@LinusU OK sounds good to me.
