### ISSUE TITLE
promise.js file is not included in module

### ISSUE THREAD

**Issue by scambier** [roryrjb/md5-file#8]
Hello,

I installed the package with `npm install --save md5-file` and got ^3.1.0, but the `promise.js` file is not included, so `require('md5-file/promise')` does not work.

**Comment by LinusU** [comment]
Whops, sorry, my bad, hang on

**Comment by LinusU** [comment]
Published as 3.1.1

**Comment by michael-ts** [comment]
@LinusU  This is strange... when I just `npm install md5-file` it installs version 2.0.7... if I `npm install md5-file@3.1.1` that works and I can use promises.

**Comment by roryrjb** [comment]
There must be a version specified in your `package.json` or a lock file somewhere, installing this module in a fresh project will install `4.0.0`.
